[package]
name = "expectation-shared"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
description = "Expectation Tests Shared Code"
license = "MIT/Apache-2.0"
edition = "2024"

[dependencies]
serde = "1"
serde_derive = "1"
walkdir = "2"
